		</section>
		<footer class="footer">
			<p><?php echo date("Y"); ?> Storm Digital</p>
			<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
				 viewBox="0 0 1920 15.4" style="enable-background:new 0 0 1920 15.4;" xml:space="preserve">
			<style type="text/css">
				.st0{fill:url(#SVGID_1_);}
			</style>
			<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="0" y1="7.7015" x2="1920" y2="7.7015">
				<stop  offset="0" style="stop-color:#128ACB"/>
				<stop  offset="1" style="stop-color:#00A870"/>
			</linearGradient>
			<rect y="0.6" class="st0" width="1920" height="14.3"/>
			</svg>

		</footer>
		<script src="<?php echo $config->urls->templates?>scripts/main.js"></script>
	</body>
</html>